### PR TITLE
Added script for patch the torch lib with the zluda's file + README cleaning

### PR DESCRIPTION
**Pull request by AlessandroMIlani**
So, the main changes are:
- Automate the copying of zluda files to the torch library (file ZludaPatch.py)
- Download zluda in subfolder .zluda if not present in ENV
  -  (but I still have to check if it works)
  
- Cleared and updated README.md 
- Created start.bat for not enable the venv and start Comfy

### CODE REVIEW

**Comment by patientx** [comment]
sorry merged without testing , I am not familiar with this github stuff, have you tested this on your pc ?

**Comment by AlessandroMIlani** [comment]
If zluda has already been added to the path, copying and renaming files works smoothly on my pc.
Now I'm trying to found a way to make the local installation work (in the .zluda folder, like for SD.next)

**Comment by patientx** [comment]
added your start.bat, and solved the zluda issue (check install.bat) , no need for python - I don't know how to code in it infact :) - since this is a windows only release. Can I use your readme as well ?

**Comment by AlessandroMIlani** [comment]
> Can I use your readme as well ?
yes, use it without any problems

>  I tested and zluda doesnt need to be on the path at all, we just need those 3 dll files inside torch lib and I did that in that batch and it worked without a zluda folder on path on first install.
Good to know, and sorry I didn't check better before making the pull request

**Pull request merged**
